### ISSUE TITLE
CrashLoopBackOff when CACHE_EXPIRATION is configured.

### ISSUE THREAD

**Issue by kishorviswanathan** [dignajar/another-ldap-auth#6]
I tried to configure ``CACHE_EXPIRATION`` via the environment in the latest docker image and the pod was crash looping.

```
Traceback (most recent call last):
  File "/opt/main.py", line 40, in <module>
    cache = Cache(CACHE_EXPIRATION)
  File "/opt/cache.py", line 8, in __init__
    self.validUntil = datetime.now() + timedelta(minutes=self.expirationMinutes)
TypeError: unsupported type for timedelta minutes component: str
```
This is the error.

I guess the problem is with the type conversion. You might want to convert the `str` value to an `int`

**Comment by dignajar** [comment]
Hi, fixed https://github.com/dignajar/another-ldap-auth/commit/2d6720458c44a14f38bf90d94d7768bf9f26d650
Thank you for report the bug.
