### ISSUE TITLE
OpenLdap Support: uid=USERNAME,ou=people,dc=server,dc=com

### ISSUE THREAD

**Issue by ricardojlrufino** [dignajar/another-ldap-auth#7]
I need change , aldap.py to
finalUsername = "uid="+self.username+","+self.searchBase

Since I don't know how to develop in python, I'm not fit for PR

**Comment by dignajar** [comment]
This issue was addressed with the variable `LDAP_BIND_DN` in ALDAP v2.0.

`LDAP_BIND_DN = "uid={username},dc=mycompany,dc=com`
